version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: libertea-mongodb
    hostname: libertea-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${PANEL_MONGODB_PASSWORD}
    volumes:
      - ./data/db:/data/db
    restart: always
    network_mode: host
    logging:
      options:
        max-size: 10m
  rsyslog:
    image: libertea/syslog
    hostname: libertea-rsyslog
    container_name: libertea-rsyslog
    restart: always
    ports:
      - "127.0.0.1:514:514/udp"
    volumes:
      - "./data/logs:/var/log/log"
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - SYSLOG
    logging:
      options:
        max-size: 10m
  log-parser:
    image: libertea/log-parser
    container_name: libertea-log-parser
    volumes:
      - "./data/logs:/data/logs"
      - "./data/usages:/data/usages"
      - "./data/parsed-logs:/data/parsed-logs"
      - "./data/all-domains-ever.lst:/data/all-domains-ever.lst:ro"
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    logging:
      options:
        max-size: 10m
  haproxy:
    environment:
      - CONN_VLESS_WS_URL=${CONN_VLESS_WS_URL}
      - CONN_VLESS_WS_IP=${CONN_VLESS_WS_IP}
      - CONN_VLESS_GRPC_URL=${CONN_VLESS_GRPC_URL}
      - CONN_VLESS_GRPC_IP=${CONN_VLESS_GRPC_IP}
      - CONN_VMESS_GRPC_URL=${CONN_VMESS_GRPC_URL}
      - CONN_VMESS_GRPC_IP=${CONN_VMESS_GRPC_IP}
      - CONN_TROJAN_WS_URL=${CONN_TROJAN_WS_URL}
      - CONN_TROJAN_WS_IP=${CONN_TROJAN_WS_IP}
      - CONN_TROJAN_GRPC_URL=${CONN_TROJAN_GRPC_URL}
      - CONN_TROJAN_GRPC_IP=${CONN_TROJAN_GRPC_IP}
      - CONN_SHADOWSOCKS_V2RAY_URL=${CONN_SHADOWSOCKS_V2RAY_URL}
      - CONN_SHADOWSOCKS_V2RAY_IP=${CONN_SHADOWSOCKS_V2RAY_IP}
      - CONN_SHADOWSOCKS_GRPC_URL=${CONN_SHADOWSOCKS_GRPC_URL}
      - CONN_SHADOWSOCKS_GRPC_IP=${CONN_SHADOWSOCKS_GRPC_IP}
      - HOSTCONTROLLER_API_KEY=${HOSTCONTROLLER_API_KEY}
      - PANEL_ADMIN_UUID=${PANEL_ADMIN_UUID}
      - PANEL_ADMIN_PASSWORD=${PANEL_ADMIN_PASSWORD}
    image: libertea/haproxy
    container_name: libertea-haproxy
    volumes:
      - ./haproxy:/usr/local/etc/haproxy/
      - ./haproxy/script.lua:/haproxy-files/script.lua
      - ./data/haproxy-lists:/haproxy-files/lists
      - /etc/ssl/ha-certs:/etc/ssl/ha-certs
      # - /var/lib/haproxy:/home/haproxy_stats
    restart: always
    network_mode: host
    logging:
      options:
        max-size: 10m
    depends_on:
      # - panel
      - log-parser
  camouflage-nginx-fallback:
    image: nginx:latest
    container_name: libertea-camouflage-nginx-fallback
    ports:
      - "127.0.0.1:25898:80"
  provider-trojan-ws:
    image: libertea/provider-trojan-ws
    network_mode: host
    container_name: libertea-provider-trojan-ws
    restart: always
    volumes:
      - './providers/trojan-ws/config.json:/etc/xray/config.json'
      - './data/certs/selfsigned/cert.pem:/etc/xray/cert.pem:ro'
      - './data/certs/selfsigned/privkey.pem:/etc/xray/privkey.pem:ro'
  provider-trojan-grpc:
    image: libertea/provider-trojan-grpc
    network_mode: host
    container_name: libertea-provider-trojan-grpc
    restart: always
    volumes:
      - './providers/trojan-grpc/config.json:/etc/xray/config.json'
      - './data/certs/selfsigned/cert.pem:/etc/xray/cert.pem:ro'
      - './data/certs/selfsigned/privkey.pem:/etc/xray/privkey.pem:ro'
  provider-vless-ws:
    image: libertea/provider-vless-ws
    network_mode: host
    container_name: libertea-provider-vless-ws
    restart: always
    volumes:
      - './providers/vless-ws/config.json:/etc/xray/config.json'
      - './data/certs/selfsigned/cert.pem:/etc/xray/cert.pem:ro'
      - './data/certs/selfsigned/privkey.pem:/etc/xray/privkey.pem:ro'
  provider-vless-grpc:
    image: libertea/provider-vless-grpc
    network_mode: host
    container_name: libertea-provider-vless-grpc
    restart: always
    volumes:
      - './providers/vless-grpc/config.json:/etc/xray/config.json'
      - './data/certs/selfsigned/cert.pem:/etc/xray/cert.pem:ro'
      - './data/certs/selfsigned/privkey.pem:/etc/xray/privkey.pem:ro'
  provider-vmess-grpc:
    image: libertea/provider-vmess-grpc
    network_mode: host
    container_name: libertea-provider-vmess-grpc
    restart: always
    volumes:
      - './providers/vmess-grpc/config.json:/etc/xray/config.json'
      - './data/certs/selfsigned/cert.pem:/etc/xray/cert.pem:ro'
      - './data/certs/selfsigned/privkey.pem:/etc/xray/privkey.pem:ro'
  
  provider-shadowsocks-v2ray:
    environment:
      - FIREWALL_OUTBOUND_UDP_PORTS=${FIREWALL_OUTBOUND_UDP_PORTS}
      - FIREWALL_OUTBOUND_TCP_PORTS=${FIREWALL_OUTBOUND_TCP_PORTS}
    image: libertea/provider-shadowsocks-v2ray
    ports:
      - "127.0.0.1:2003:2003"
    cap_add:
      - NET_ADMIN
    container_name: libertea-provider-shadowsocks-v2ray
    restart: always
    volumes:
      - './providers/shadowsocks-v2ray/config.env:/etc/xray/config.env'
  # provider-shadowsocks-grpc:
  #   environment:
  #     - FIREWALL_OUTBOUND_UDP_PORTS=${FIREWALL_OUTBOUND_UDP_PORTS}
  #     - FIREWALL_OUTBOUND_TCP_PORTS=${FIREWALL_OUTBOUND_TCP_PORTS}
  #   build: ./providers/shadowsocks-grpc
  #   ports:
  #     - "127.0.0.1:2006:2006"
  #   cap_add:
  #     - NET_ADMIN
  #   container_name: libertea-provider-shadowsocks-grpc
  #   restart: always
  #   volumes:
  #     - './providers/shadowsocks-grpc/config.json:/etc/xray/config.json'
  #     - './data/certs/selfsigned/cert.pem:/etc/xray/cert.pem:ro'
  #     - './data/certs/selfsigned/privkey.pem:/etc/xray/privkey.pem:ro'
  provider-outbound-warp:
    environment:
      - FIREWALL_OUTBOUND_UDP_PORTS=${FIREWALL_OUTBOUND_UDP_PORTS}
      - FIREWALL_OUTBOUND_TCP_PORTS=${FIREWALL_OUTBOUND_TCP_PORTS}
    image: libertea/provider-outbound-warp
    privileged: true
    ports:
      - "127.0.0.1:2997:2997"
    container_name: libertea-provider-outbound-warp
    restart: always
    volumes:
      - './providers/outbound-warp/config.json:/etc/xray/config.json'
  provider-outbound-direct:
    environment:
      - FIREWALL_OUTBOUND_UDP_PORTS=${FIREWALL_OUTBOUND_UDP_PORTS}
      - FIREWALL_OUTBOUND_TCP_PORTS=${FIREWALL_OUTBOUND_TCP_PORTS}
    image: libertea/provider-outbound-direct
    ports:
      - "127.0.0.1:2998:2998"
    container_name: libertea-provider-outbound-direct
    restart: always
    volumes:
      - './providers/outbound-direct/config.json:/etc/xray/config.json'
