name: Publish Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"



jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: "Getting Version Number"
        id: version
        run: number=$(cat version.txt)
        env:
          number: $number

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Haproxy Version
        uses: docker/build-push-action@v4
        with:
          context: ./haproxy
          platforms: linux/amd64,linux/arm64
          push: true
          tags: liberteamarron/haproxy:${{ steps.version.number }}


      - name: Build and Push Haproxy Latest
        uses: docker/build-push-action@v4
        with:
          context: ./haproxy
          platforms: linux/amd64,linux/arm64
          push: true
          tags: liberteamarron/haproxy:latest



